//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvSQLCompact
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HidroMobileEntities : DbContext
    {
        public HidroMobileEntities()
            : base("name=HidroMobileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCadastro> tblCadastro { get; set; }
        public virtual DbSet<tblLeitura> tblLeitura { get; set; }
        public virtual DbSet<tblLog> tblLog { get; set; }
        public virtual DbSet<tblOcor> tblOcor { get; set; }
        public virtual DbSet<tblRota> tblRota { get; set; }
        public virtual DbSet<tblSistemaAbast> tblSistemaAbast { get; set; }
        public virtual DbSet<tblTarifaTabelas> tblTarifaTabelas { get; set; }
        public virtual DbSet<tblTarifaTabelasCategoria> tblTarifaTabelasCategoria { get; set; }
        public virtual DbSet<tblEncargos> tblEncargos { get; set; }
        public virtual DbSet<tblLogra> tblLogra { get; set; }
        public virtual DbSet<tblMensagem> tblMensagem { get; set; }
        public virtual DbSet<tblPosicao> tblPosicao { get; set; }
    }
}
