//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvSQLCompact
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCadastro
    {
        public int CodConta { get; set; }
        public Nullable<int> NumRes { get; set; }
        public Nullable<int> NumCom { get; set; }
        public Nullable<int> NumInd { get; set; }
        public Nullable<int> NumPub { get; set; }
        public string Hidrometro { get; set; }
        public Nullable<int> TipoLigacao { get; set; }
        public Nullable<int> Piscina { get; set; }
        public Nullable<int> CaoBravo { get; set; }
        public Nullable<int> AlterouCad { get; set; }
        public Nullable<int> NumSoc { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Complemento { get; set; }
    }
}
