//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvSQLCompact
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLog
    {
        public Nullable<System.DateTime> DataSistema { get; set; }
        public int CodReg { get; set; }
        public string Versao { get; set; }
    }
}
