//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvSQLCompact
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogra
    {
        public int CodLogra { get; set; }
        public string NomeLogra { get; set; }
        public string Bairro { get; set; }
        public Nullable<int> TotContas { get; set; }
    }
}
