//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvSQLCompact
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOcor
    {
        public int CodOcor { get; set; }
        public string DescOcor { get; set; }
        public Nullable<short> ObterMedia { get; set; }
        public Nullable<short> MostraNaConta { get; set; }
        public Nullable<short> EvitaFreq { get; set; }
        public Nullable<short> ExigeLeitura { get; set; }
    }
}
