//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvSQLCompact
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRota
    {
        public int CodRegiaoRota { get; set; }
        public string DescRota { get; set; }
        public Nullable<int> TotContas { get; set; }
        public Nullable<int> CodUsuario { get; set; }
        public string NomeUsuario { get; set; }
        public Nullable<System.DateTime> MesFat { get; set; }
        public Nullable<System.DateTime> DataLiberacao { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> ProximaLeitura { get; set; }
        public Nullable<int> PosIniImpressao { get; set; }
        public string PixChave { get; set; }
        public string PixMerchantName { get; set; }
        public string PixTXIDPrefixo { get; set; }
        public string PixMerchantCity { get; set; }
    }
}
