//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvSQLCompact
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSistemaAbast
    {
        public int CodRegiaoRota { get; set; }
        public System.DateTime Mesfat { get; set; }
        public int CodSistemaAbast { get; set; }
        public Nullable<System.DateTime> DataInicial { get; set; }
        public Nullable<System.DateTime> DataFinal { get; set; }
        public string TurbidezUnidade { get; set; }
        public string TurbidezValorMaxPermitido { get; set; }
        public string TurbidezValorMedioDetectado { get; set; }
        public string TurbidezAmostrasPadrao { get; set; }
        public string TurbidezAnalisadas { get; set; }
        public string CorUnidade { get; set; }
        public string CorValorMaxPermitido { get; set; }
        public string CorValorMedioDetectado { get; set; }
        public string CorAmostrasPadrao { get; set; }
        public string CorAnalisadas { get; set; }
        public string PHUnidade { get; set; }
        public string PHValorMaxPermitido { get; set; }
        public string PHAnalisadas { get; set; }
        public string PHValorMedioDetectado { get; set; }
        public string PHAmostrasPadrao { get; set; }
        public string CloroUnidade { get; set; }
        public string CloroValorMaxPermitido { get; set; }
        public string CloroValorMedioDetectado { get; set; }
        public string CloroAmostrasPadrao { get; set; }
        public string CloroAnalisadas { get; set; }
        public string ColiformesUnidade { get; set; }
        public string ColiformesValorMaxPermitido { get; set; }
        public string ColiformesValorMedioDetectado { get; set; }
        public string ColiformesAmostrasPadrao { get; set; }
        public string ColiformesAnalisadas { get; set; }
        public string FluorUnidade { get; set; }
        public string FluorValorMaxPermitido { get; set; }
        public string FluorAnalisadas { get; set; }
        public string FluorValorMedioDetectado { get; set; }
        public string FluorAmostrasPadrao { get; set; }
    }
}
