//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvSQLCompact
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTarifaTabelas
    {
        public int CodTabela { get; set; }
        public string DescTabela { get; set; }
        public Nullable<System.DateTime> DataVigor { get; set; }
        public Nullable<int> CodTabelaOrigem { get; set; }
        public bool ReajusteProporcional { get; set; }
    }
}
