//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvSQLCompact
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTarifaTabelasCategoria
    {
        public int CodTabela { get; set; }
        public int Faixa { get; set; }
        public Nullable<double> AguaRes { get; set; }
        public Nullable<double> EsgotoRes { get; set; }
        public Nullable<double> ValorFaixaRes { get; set; }
        public Nullable<double> ValorFaixaResEsg { get; set; }
        public Nullable<double> AguaCom { get; set; }
        public Nullable<double> EsgotoCom { get; set; }
        public Nullable<double> ValorFaixaCom { get; set; }
        public Nullable<double> ValorFaixaComEsg { get; set; }
        public Nullable<double> AguaInd { get; set; }
        public Nullable<double> EsgotoInd { get; set; }
        public Nullable<double> ValorFaixaInd { get; set; }
        public Nullable<double> ValorFaixaIndEsg { get; set; }
        public Nullable<double> AguaPub { get; set; }
        public Nullable<double> EsgotoPub { get; set; }
        public Nullable<double> ValorFaixaPub { get; set; }
        public Nullable<double> ValorFaixaPubEsg { get; set; }
        public Nullable<double> AguaSoc { get; set; }
        public Nullable<double> EsgotoSoc { get; set; }
        public Nullable<double> ValorFaixaSoc { get; set; }
        public Nullable<double> ValorFaixaSocEsg { get; set; }
        public Nullable<double> AguaResAnt { get; set; }
        public Nullable<double> EsgotoResAnt { get; set; }
        public Nullable<double> ValorFaixaResAnt { get; set; }
        public Nullable<double> ValorFaixaResEsgAnt { get; set; }
        public Nullable<double> AguaComAnt { get; set; }
        public Nullable<double> EsgotoComAnt { get; set; }
        public Nullable<double> ValorFaixaComAnt { get; set; }
        public Nullable<double> ValorFaixaComEsgAnt { get; set; }
        public Nullable<double> AguaIndAnt { get; set; }
        public Nullable<double> EsgotoIndAnt { get; set; }
        public Nullable<double> ValorFaixaIndAnt { get; set; }
        public Nullable<double> ValorFaixaIndEsgAnt { get; set; }
        public Nullable<double> AguaPubAnt { get; set; }
        public Nullable<double> EsgotoPubAnt { get; set; }
        public Nullable<double> ValorFaixaPubAnt { get; set; }
        public Nullable<double> ValorFaixaPubEsgAnt { get; set; }
        public Nullable<double> AguaSocAnt { get; set; }
        public Nullable<double> EsgotoSocAnt { get; set; }
        public Nullable<double> ValorFaixaSocAnt { get; set; }
        public Nullable<double> ValorFaixaSocEsgAnt { get; set; }
    }
}
